export const audioData = [
  {
    id: 1,
    performer: 'I Monster',
    title: 'Daydream In Blue',
    src: '/audio/BhB6Lb7_kN8.mp3',
  },
  {
    id: 2,
    performer: 'Romperayo',
    title: 'Alegria por un Zumo de Naranja Con Panela',
    src: '/audio/9PLqb-RxIak.mp3',
  },
  {
    id: 3,
    performer: 'The Cinematic Orchestra',
    title: 'All That You Give',
    src: '/audio/5w9t2AL4M28.mp3',
  },
  {
    id: 4,
    performer: 'Los macuanos',
    title: 'Alma',
    src: '/audio/VNxcuwrNMwc.mp3',
  },
  {
    id: 5,
    performer: 'Astrud Gilberto',
    title: 'Água de Beber',
    src: '/audio/O0gzsR-40Bw.mp3',
  },
  {
    id: 6,
    performer: 'Betty Chung',
    title: 'Bang Bang',
    src: '/audio/ZmnQHf2H64o.mp3',
  },
  {
    id: 7,
    performer: 'Bonga',
    title: 'Roça de jindungo',
    src: '/audio/b_NoWKAk4U0.mp3',
  },
  {
    id: 8,
    performer: 'Braveyoung',
    title: 'Flesh and Bone',
    src: '/audio/f9lJT3CcNl0.mp3',
  },
  {
    id: 9,
    performer: 'São Paris',
    title: 'Butterfly',
    src: '/audio/4Nat0fjY4JA.mp3',
  },
  {
    id: 10,
    performer: 'Barbatuques',
    title: 'Cheiro Verde',
    src: '/audio/6jApmqXnMuI.mp3',
  },
  {
    id: 11,
    performer: 'Marcelo Martins',
    title: 'Coisa nº 9',
    src: '/audio/WmWBAKwgMFk.mp3',
  },
  {
    id: 12,
    performer: 'Ramsey Lewis',
    title: 'Cry Baby Cry',
    src: '/audio/2Apo8XLmPs8.mp3',
  },
  {
    id: 13,
    performer: "Mo' Horizons",
    title: 'Dance Naked Under Palmtrees',
    src: '/audio/3MuBIv0UGJ8.mp3',
  },
  {
    id: 14,
    performer: 'Espíritu Balanta',
    title: 'JuGa Music',
    src: '/audio/BIwC91Esri4.mp3',
  },
  {
    id: 15,
    performer: 'Erik Truffaz',
    title: 'Down Town',
    src: '/audio/UFdUSM9UEYs.mp3',
  },
  {
    id: 16,
    performer: 'Nuri',
    title: 'Drup',
    src: '/audio/xrR8_XV6Q8M.mp3',
  },
  {
    id: 17,
    performer: 'Wax One',
    title: 'Dust & Groove',
    src: '/audio/7vuRazXY6mQ.mp3',
  },
  {
    id: 18,
    performer: 'Efterklang',
    title: 'Dreams Today',
    src: '/audio/wTG1f7Uhldo.mp3',
  },
  {
    id: 19,
    performer: 'Efterklang',
    title: 'Lyset',
    src: '/audio/QyvZcMx6K-0.mp3',
  },
  {
    id: 20,
    performer: 'Hermanos Gutiérrez',
    title: 'El Camino De Mi Alma',
    src: '/audio/OU-zqNVPqw0.mp3',
  },
  {
    id: 21,
    performer: 'Fazer',
    title: 'Grenadier (Official Video)',
    src: '/audio/ILFq6iDhOcM.mp3',
  },
  {
    id: 22,
    performer: 'naked Roommate',
    title: 'Fondu Guru',
    src: '/audio/dCFuumQKpN0.mp3',
  },
  {
    id: 23,
    performer: 'Piero Umiliani',
    title: 'Fuga in Jazz',
    src: '/audio/TVSVhEbTem8.mp3',
  },
  {
    id: 24,
    performer: 'Plastilina Mosh',
    title: 'Goodbye Happy Farm',
    src: '/audio/Aq_yh1eV9Wk.mp3',
  },
  {
    id: 25,
    performer: 'Ryuichi Sakamoto',
    title: 'Inútil Paisagem',
    src: '/audio/dGgl0VMJbPA.mp3',
  },
  {
    id: 26,
    performer: 'Lady & Bird',
    title: 'La Ballade of Lady and Bird',
    src: '/audio/8iEx_pfOSNA.mp3',
  },
  {
    id: 27,
    performer: 'Les Mamans du Congo & RROBIN',
    title: 'Meki',
    src: '/audio/iEc9V92yAYQ.mp3',
  },
  {
    id: 28,
    performer: 'Monsieur Charles',
    title: 'Life',
    src: '/audio/JBIgeBKWuhY.mp3',
  },
  {
    id: 29,
    performer: 'Liquid Liquid',
    title: 'Scraper',
    src: '/audio/bJHqR6PqDV4.mp3',
  },
  {
    id: 30,
    performer: 'Mokyo',
    title: 'MAD',
    src: '/audio/PSGg9udzhfg.mp3',
  },
  {
    id: 31,
    performer: 'Congotronics International',
    title: 'Many Tongues In Our Band',
    src: '/audio/IxtD5f43Olk.mp3',
  },
  {
    id: 32,
    performer: 'Bambooman',
    title: 'Melt (Original Mix)',
    src: '/audio/VqmXps49-4g.mp3',
  },
  {
    id: 33,
    performer: 'Mushroom',
    title: 'Can',
    src: '/audio/T_9LJCKOvQE.mp3',
  },
  {
    id: 34,
    performer: 'Leonard Nimoy',
    title: 'Music To Watch Space Girls By',
    src: '/audio/FDggMLJqhj0.mp3',
  },
  {
    id: 35,
    performer: 'Naomi',
    title: 'Anybody Here?',
    src: '/audio/xyt9ZbY4bD0.mp3',
  },
  {
    id: 36,
    performer: "Aaron Kelly's Bones",
    title: 'Needful Things',
    src: '/audio/BOyN6eP24yg.mp3',
  },
  {
    id: 37,
    performer: 'Bonga Jean-Baptiste',
    title: 'Ogoun',
    src: '/audio/1FGYlCqrJ7k.mp3',
  },
  {
    id: 38,
    performer: 'The Unbending Trees',
    title: 'Overture',
    src: '/audio/5gY25E9r_4c.mp3',
  },
  {
    id: 39,
    performer: 'Plastilina Mosh',
    title: 'Paso Fino',
    src: '/audio/Nu2PA0-IT4w.mp3',
  },
  {
    id: 40,
    performer: 'Bopol Mansiamina',
    title: 'Pitié je veux la réconciliation',
    src: '/audio/5XVz291WwjQ.mp3',
  },
  {
    id: 41,
    performer: 'Anónimo',
    title: 'Que bella es la navidad',
    src: '/audio/eudPVC0kWnY.mp3',
  },
  {
    id: 42,
    performer: 'Rework',
    title: 'October Love Song (Chris & Cosey Cover)',
    src: '/audio/y0uolbPs0Og.mp3',
  },
  {
    id: 43,
    performer: 'Piero Umiliani',
    title: 'Risaie',
    src: '/audio/b_-nuiaRFL0.mp3',
  },
  {
    id: 44,
    performer: 'Liquid Liquid',
    title: 'Scraper',
    src: '/audio/DsdamQ7r0Is.mp3',
  },
  {
    id: 45,
    performer: 'Sidsel Endresen & Bugge Wesseltoft',
    title: 'Out here. In...',
    src: '/audio/UBRVI5uaIM4.mp3',
  },
  {
    id: 46,
    performer: 'Loren Connors',
    title: 'Tall Grass',
    src: '/audio/te2CUhLz62U.mp3',
  },
  {
    id: 47,
    performer: 'Funki Porcini',
    title: 'The Big Sea',
    src: '/audio/JiPlXKlS7tg.mp3',
  },
  {
    id: 48,
    performer: 'Chilli Gonzales',
    title: 'The Tourist',
    src: '/audio/X52i1ydm4qM.mp3',
  },
  {
    id: 49,
    performer: 'Thiago França',
    title: 'A Espetacular Charanga do França: Bragadá',
    src: '/audio/lkSpqBD8Tx8.mp3',
  },
  {
    id: 50,
    performer: 'Tindersticks',
    title: 'This Fear of Emptiness',
    src: '/audio/Wfb_It-JlgM.mp3',
  },
  {
    id: 51,
    performer: "Tower Of Meaning/Rabbit's Ear",
    title: 'Home Away From Home',
    src: '/audio/1fiCv6RdZmA.mp3',
  },
  {
    id: 52,
    performer: 'Emanative',
    title: 'Turn Your Lights On (feat. Ahu)',
    src: '/audio/r1WSk3vrctg.mp3',
  },
  {
    id: 53,
    performer: 'Quilapayún',
    title: 'Vals de Colombes',
    src: '/audio/EMn1fx-RalE.mp3',
  },
  {
    id: 54,
    performer: 'The Soul Surfers',
    title: 'Wavy',
    src: '/audio/0h9JlCBXKNk.mp3',
  },
  {
    id: 55,
    performer: 'Funki Porcini',
    title: 'What Are You Looking At?',
    src: '/audio/kMeT0F3mQek.mp3',
  },
  {
    id: 56,
    performer: 'Şatellites',
    title: 'Yar Oi (Batov Records)',
    src: '/audio/etWIwbcPmUM.mp3',
  },
  {
    id: 57,
    performer: 'Roberto Carlos',
    title: 'Que será de ti',
    src: '/audio/CekB_6hjf5E.mp3',
  },
  {
    id: 58,
    performer: "Aphrodite's Child",
    title: 'The End of The World',
    src: '/audio/xWndjqMwBu4.mp3',
  },
  {
    id: 59,
    performer: 'Aventura (Feat. Bad Bunny)',
    title: 'Volví',
    src: '/audio/5IzfIoQvnuw.mp3',
  },
  {
    id: 60,
    performer: 'Gram Rabbit',
    title: 'Dirty Horse',
    src: '/audio/CYPtQ6w_KG4.mp3',
  },
];
